package org.schabi.newpipe.player.subtitles;

import android.content.Context;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

import org.schabi.newpipe.extractor.NewPipe;
import org.schabi.newpipe.extractor.downloader.Downloader;
import org.schabi.newpipe.extractor.downloader.Response;
import org.schabi.newpipe.extractor.stream.StreamInfo;
import org.schabi.newpipe.extractor.stream.SubtitlesStream;

import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.crypto.Cipher;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;

/**
 * Loads a member-subtitle encrypted file (.enc) from the repo and decrypts it with
 * key = SHA-256(该视频自动字幕的"真实文本"). The plaintext is the original .ass/.srt, parsed by
 * {@link AssSubtitleParser}. 与 ass-subtitle-overlay 插件端的 key 一致：
 * key 源 = 自动字幕真实文本（srt3 的 &lt;p&gt; 段，与 PC 端 protobuf segs.utf8 同内容）。
 */
public final class MemberSubtitleLoader {

    private MemberSubtitleLoader() {
    }

    /** Fetch + decrypt + parse the member .enc subtitle for the given repo id. */
    @NonNull
    public static List<SubtitleLine> load(final Context context, final String baseUrl,
                                          final String id, @Nullable final StreamInfo info) {
        final byte[] enc = fetchEnc(baseUrl, id);
        if (enc == null || enc.length <= 28) {
            return new ArrayList<>();
        }
        final String captionText = fetchCaptionSegmentText(info);
        if (captionText == null || captionText.isEmpty()) {
            return new ArrayList<>();
        }
        try {
            final String canon = canonCaptionText(captionText);
            final byte[] key = sha256(canon);
            final byte[] nonce = java.util.Arrays.copyOfRange(enc, 0, 12);
            final byte[] data = java.util.Arrays.copyOfRange(enc, 12, enc.length); // ct||tag
            final Cipher cipher = Cipher.getInstance("AES/GCM/NoPadding");
            cipher.init(Cipher.DECRYPT_MODE, new SecretKeySpec(key, "AES"),
                    new GCMParameterSpec(128, nonce));
            final byte[] plain = cipher.doFinal(data);
            final String text = new String(plain, java.nio.charset.StandardCharsets.UTF_8);
            if (text.isEmpty()) {
                return new ArrayList<>();
            }
            return AssSubtitleParser.parse(text);
        } catch (final Exception e) {
            return new ArrayList<>();
        }
    }

    @Nullable
    private static byte[] fetchEnc(final String baseUrl, final String id) {
        final String base = trimSlash(baseUrl);
        final String[] exts = {".ass.enc", ".srt.enc", ".enc"};
        for (final String ext : exts) {
            try {
                final Downloader dl = NewPipe.getDownloader();
                final Response r = dl.get(base + "/" + java.net.URLEncoder.encode(id, "UTF-8") + ext);
                if (r.responseCode() >= 200 && r.responseCode() < 300) {
                    final byte[] body = r.rawResponseBody() != null ? r.rawResponseBody() : new byte[0];
                    if (body.length == 0) {
                        return null;
                    }
                    return body;
                }
            } catch (final Exception e) {
                // try next
            }
        }
        return null;
    }

    @Nullable
    private static String fetchCaptionSegmentText(@Nullable final StreamInfo info) {
        if (info == null) {
            return null;
        }
        final List<SubtitlesStream> subs = info.getSubtitles();
        if (subs == null || subs.isEmpty()) {
            return null;
        }
        SubtitlesStream pick = null;
        for (final SubtitlesStream s : subs) {
            if (s.isAutoGenerated()) { pick = s; break; }
        }
        if (pick == null) { pick = subs.get(0); }
        final String url = pick.getContent();
        if (url == null || url.isEmpty()) {
            return null;
        }
        try {
            final Downloader dl = NewPipe.getDownloader();
            final Response r = dl.get(url);
            if (r.responseCode() >= 200 && r.responseCode() < 300) {
                return r.responseBody();
            }
        } catch (final Exception e) {
            // ignore
        }
        return null;
    }

    @NonNull
    static String canonCaptionText(final String s) {
        final Matcher tm = Pattern.compile(">([^<>]{1,})<").matcher(s);
        final StringBuilder tb = new StringBuilder();
        boolean tf = false;
        while (tm.find()) {
            final String c = tm.group(1).trim();
            if (!c.isEmpty()) {
                if (tf) { tb.append('\n'); }
                tb.append(c);
                tf = true;
            }
        }
        if (tf) {
            return tb.toString();
        }
        return s;
    }

    private static byte[] sha256(final String s) throws Exception {
        final MessageDigest md = MessageDigest.getInstance("SHA-256");
        return md.digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8));
    }

    private static String trimSlash(final String s) {
        if (s == null) { return ""; }
        String t = s;
        while (t.endsWith("/")) { t = t.substring(0, t.length() - 1); }
        return t;
    }
}